import matter from 'gray-matter'

/**
 * Strip YAML frontmatter and KB creator artifacts from markdown content
 * before it is passed to the unified HTML pipeline.
 *
 * Articles generated by the KB creator sometimes include:
 * - YAML frontmatter (---...---) at the top, which renders as raw text
 * - <hyperlink>slug</hyperlink> tags that are internal KB creator artifacts
 */
export function preprocessMarkdown(markdown: string): string {
  // Normalize CRLF to LF so gray-matter works correctly on Windows-generated content
  const normalized = markdown.replace(/\r\n/g, '\n').trimStart()

  // Strip YAML frontmatter if present
  const { content } = matter(normalized)

  // Strip any <hyperlink>...</hyperlink> tags left by the KB creator
  const stripped = content.replace(/<hyperlink>[^<]*<\/hyperlink>/g, '')

  return stripped
}
