import matter from 'gray-matter'

/**
 * Strip YAML frontmatter and KB creator artifacts from markdown content
 * before it is passed to the unified HTML pipeline.
 *
 * Articles generated by the KB creator sometimes include:
 * - YAML frontmatter (---...---) at the top, which renders as raw text
 * - <hyperlink>slug</hyperlink> tags that are internal KB creator artifacts
 * - A leading # h1 heading that duplicates the template-rendered title
 */
export function preprocessMarkdown(markdown: string): string {
  // Normalize CRLF to LF so gray-matter works correctly on Windows-generated content
  const normalized = markdown.replace(/\r\n/g, '\n').trimStart()

  // Strip YAML frontmatter if present — fall back to raw content if YAML is malformed
  let content: string
  try {
    content = matter(normalized).content
  } catch {
    content = normalized.replace(/^---[\s\S]*?---\n?/, '')
  }

  // Strip any <hyperlink>...</hyperlink> tags left by the KB creator
  const stripped = content.replace(/<hyperlink>[^<]*<\/hyperlink>/g, '')

  // Strip the leading # h1 heading — the page template renders the article
  // title in its own <h1>, so having a second # Title in the content body
  // creates duplicate h1 tags (SEO penalty). Strip only the FIRST # heading.
  // Note: \s* intentionally matches any leading newline that gray-matter
  // may leave before the first heading — this is correct behaviour.
  // If content does not start with an h1, the regex safely matches nothing.
  const withoutLeadingH1 = stripped.replace(/^\s*# [^\n]+\n?/, '')

  return withoutLeadingH1
}
